version: '3.7'

services: 
  postgres: 
    image: 'postgres:13'
    restart: always
    env_file: '.env'
    environment:
       - POSTGRES_DB=${DB_NAME_MS}
       - POSTGRES_USER=${DB_USER_MS}
       - POSTGRES_PASSWORD=/run/secrets/db_password_ms
    ports:
       - 5433:5432
    # persiste la informacion en un volumen local
    volumes:
       - './postgres_data:/var/lib/postgresql/data'
    secrets:
       - db_password_ms

  pgadmin: 
    image: dpage/pgadmin4
    env_file: '.env'
    environment:
       - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
       #- PGADMIN_DEFAULT_PASSWORD=/run/secrets/pgadmin_password
       - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
       - 5050:80   
    #secrets:
    #   - pgadmin_password
secrets:
   db_password_ms:
     file: db_password_ms.txt
   pgadmin_password:
     file: pgadmin_password.txt

